### ISSUE TITLE
A.1. Reservation

### ISSUE THREAD

**Issue by sumayyah42** [core-initiative/front-desk#1]
## Layout
![image](https://user-images.githubusercontent.com/25950059/75148203-a155f300-5731-11ea-92d5-54acae2c2316.png)
![image](https://user-images.githubusercontent.com/25950059/75214876-8763f100-57c1-11ea-95cd-84ce7e647428.png)

## Precondition
1. Record Customer telah dibuat
2. Terdapat kamar yang available

## Basic Flow
1. Klik new pada halaman Reservation
2. Pilih rentang tanggal untuk menginap
3. Pilih kamar yang available (tidak dibooking) pada rentang tanggal tersebut
4. Pilih room rate yang sudah difilter berdasarkan tipe kamar
5. Klik tombol save

## Alternate Flow
 3.1.	Pilih room type dan bed type 
 3.2. Pilih kamar yang available (tidak dibooking) pada rentang tanggal, room type, dan bed type
 4.1. Ubah Amount Room Rate menjadi lebih rendah dari bottom rate, menampilkan error
 5.1. Setelah klik save, isian yang required belum lengkap terisi. Muncul modal warning dan kembali ke halaman Reservation 
5.2. Setelah klik save, isian lengkap maka akan membuat record baru sebagai berikut: 	
- Membuat record di doctype Reservation (contoh reservation individual)

| Field | Doctype Type | Value |
| - | - | - |
| name | format:RSV-{####} | RSV-XXX | 
| customer_id | Link | form.customer |
| type | Select | Individual |
| reserved_room_id | Link | form.room |
| actual_room_id | Link | null |
| room_type | Link | form.room_type |
| bed_type | Link | form.bed_type |
| group_id | Link | null |
| channel | Link | form.channel |
| guest_name | Data | form.guest_name |
| room_rate | Link | form.room_rate |
| actual_rate | Currency | form.actual_rate |
| expected_arrival | Date and Time | form.arrival |
| expected_departure | Date and Time | form.departure |
| actual_arrival | Date and Time | null |
| actual_departure | Date and Time | null |
| adult | Int | form.adult |
| child | Int | form.child |
| extra_bed | Int | form.extra_bed |
| status | Select | Reserved |
| wifi_password | Data | null |

dan child table Room Rate Breakdown (untuk pembagian nominal ke setiap komponen jika diubah menjadi lebih besar)
| Field | Type | Value |
| - | - | - |
| breakdown_room_rate | Currency | (actual_rate - (room_rate.breakfast_rate+room_rate.breakfast_tax)/121 x 100 |
| room_rate_tax | Link (Inn Tax) | room_rate.room_rate_tax |
| breakfast_rate | Currency | room_rate.breakfast_rate |
| breakfast_tax | Link(Inn Tax) | room_rate.breakfast_tax |

- Membuat record di doctype Room Booking 

| Field | Doctype Type | Value |
| - | - | - |
| start | Date and Time | form.arrival |
| end | Date and Time | form.departure|
| status | select | Booked |
| room_id | Link | form.room |
| room_availability | Select | RS |
| reservation_id | Link | RSV-XXX |

- Membuat record di doctype Folio

| Attribute | Type | Value |
| - | - | - |
| open | Datetime | reservation.expected_arrival |
| close | Datetime | reservation.expected_departure |
| type | Select | Guest |
| parent_id | Link | null |
| group_name | Link | form.group_id |
| status | Select | Open |
| customer_id | Link | form.customer |

## Post Condition
1. Record reservation tersimpan
2. Room yang dipilih akan berstatus Booked di rentang tanggal yang dipilih
3. Guest Folio generated

**Comment by anra54** [comment]
karena struktur baru doctype `Inn Reservation`, yaitu field `room_type`, `bed_type`, dan `room_id`/`actual_room_id` yang tidak berada di child table, maka fitur `room_type` dan `bed_type` yang akan **otomatis terisi** jika field `room_id`/`actual_room_id` yang dipilih,  sementara belum bisa diterapkan.
Sementara, alur yang harus diikuti adalah mengisi `room_type` dan `bed_type` **terlebih dahulu** sebelum memilih `room_id`/ `actual_room_id`.

**Comment by sumayyah42** [comment]
Improve : atribut Folio ditambahakan value start dan end yang diambil dari expected arrival dan expected departure

**Comment by anra54** [comment]
> Improve : atribut Folio ditambahakan value start dan end yang diambil dari expected arrival dan expected departure

di [sini](https://github.com/purwaren/front-desk/issues/13#issuecomment-602323626) namanya open close, satunya datetime satunya date.. yg mana yg ultimate nih?

**Comment by sumayyah42** [comment]
Open Close
