### ISSUE TITLE
A.2. Check In

### ISSUE THREAD

**Issue by sumayyah42** [core-initiative/front-desk#2]
## Contoh Layout setelah check in
![image](https://user-images.githubusercontent.com/25950059/75148203-a155f300-5731-11ea-92d5-54acae2c2316.png)
![image](https://user-images.githubusercontent.com/25950059/75214600-b3cb3d80-57c0-11ea-85bc-e7f6de23af0c.png)
![image](https://user-images.githubusercontent.com/25950059/75215436-4a98f980-57c3-11ea-99ac-ce252b931ee1.png)

## Precondition
1. Reservation telah dibuat

## Basic Flow
1. Pilih reservation yang akan di check in
2. Klik tombol check in
3. Klik tombol save

## Alternate Flow
3.1.	Kamar belum berstatus vacant ready, pilih kamar kembali 

### Note untuk tampilan form ketika check in
- field expected room di-hide
- field room, di filter seperti saat reservasi (berdasarkan status room booking di rentang arrival departure, room type, bed type) ditambah pengecekan status room = Vacant Ready

## Post Condition
1. Set actual_arrival reservation menjadi current_datetime ketika klik check in 
2. Status reservation berubah menjadi In house
3. Wifi Password pada reservation terisi
4. Child table Issued Card muncul
5. if initial_room_id != room_id (dan tidak ada perubahan tanggal arrival departure), update record pada room booking sebagai berikut
```
update room_booking
set room_id = reservation.room_id
where reservation = reservation.name
```

**Comment by sumayyah42** [comment]
Saat klik tombol Start Check In Process, Field Room Type terisi dengan value berikut
![image](https://user-images.githubusercontent.com/25950059/77291395-c3329d80-6d10-11ea-840f-9208d6dad856.png)
padahal value saat sebelum check in bukan itu

**Comment by anra54** [comment]
> Saat klik tombol Start Check In Process, Field Room Type terisi dengan value berikut
> ![image](https://user-images.githubusercontent.com/25950059/77291395-c3329d80-6d10-11ea-840f-9208d6dad856.png)
> padahal value saat sebelum check in bukan itu

fixed at 577d283c6c2e425ef73c283c20f639e6324ac1df

**Comment by sumayyah42** [comment]
Status Inn Room yang ditempati diupdate menjadi Occupied Clean, saat ini statusnya adalah Occupied Dirty

**Comment by anra54** [comment]
> Status Inn Room yang ditempati diupdate menjadi Occupied Clean, saat ini statusnya adalah Occupied Dirty

Bukannya sedari dulu (front desk) kalo check in jadi occupied dirty? 
[reservation.js front_desk](https://github.com/purwaren/ihram-front-desk/blob/1059ceed4a1426d2c507565d61634fbd822e4adf/front_desk/front_desk/doctype/reservation/reservation.js#L383)

**Comment by sumayyah42** [comment]
- Room yang berubah statusnya menjadi Occupied Clean adalah actual_room. Saat ini yang berubah adalah kamar yang ada pada reserved_room
- Field actual_room saat ini menampilkan seluruh kamar tanpa ada filter. Terapkan filter seperti pada reserved_room ditambah dengan filter status == vacant ready, supaya kamar yang dipilih adalah kamar yang available dari booking-an tamu lain dan siap dipakai
