### ISSUE TITLE
C.4. Print Cashier Report

### ISSUE THREAD

**Issue by sumayyah42** [core-initiative/front-desk#23]
## Precondition
1. Terdapat record Shift

## Basic Flow
1. Pilih salah satu record Shift
2. Klik tombol Print Cashier Remittance

## Post Condition
1. Menampilkan print format Cashier Report yang terdiri dari
   - detail pembayaran dari berbagai mode of payment
   - payment summary dari setiap mode of payment
   - kolom tanda tangan penyetor dan penerima 
contoh print sebagai berikut
 [CashierReport02-RealData.pdf](https://github.com/purwaren/ihram-front-desk/files/4063513/CashierReport02-RealData.pdf)

**Comment by anra54** [comment]
yang kemarin formatnya mengikuti yang dari [CashierReport02-RealData.pdf](https://github.com/purwaren/ihram-front-desk/files/4063513/CashierReport02-RealData.pdf)
Berubah lagi atau salah attach file pdf nih?

**Comment by sumayyah42** [comment]
Iya salah maap. Ga berubah dari yg sebelumnya
