### ISSUE TITLE
D.3. Dayend Close

### ISSUE THREAD

**Issue by sumayyah42** [core-initiative/front-desk#28]
## Precondition
1. Sudah melakukan Posting Room Charge

## Basic Flow
1. Klik menu Dayend Close
2. Klik tombol New
3. Sistem menampilkan Reservation yang expected arrival hari ini tapi belum check in, Reservation yang expected departure hari ini tapi belum check out dan Folio yang harus Close hari ini tapi belum di Close. Contoh layout
![image](https://user-images.githubusercontent.com/25950059/77143679-7489c700-6ab6-11ea-9572-5a1ad06517be.png)
![image](https://user-images.githubusercontent.com/25950059/77273368-fdd31080-6ce5-11ea-86e8-d018380e4066.png)
Note: untuk Folio yang seharusnya di Close, ditampilkan hanya yang bertipe Master dan Desk. Untuk Guest Folio supaya di Close melalui check out Reservation.
4. Klik id reservation yang tertera untuk memproses check in/cancel/no show/check out/extend menginap.
5. Setelah diproses, description tabel bisa berubah ataupun recordnya dihilangkan (untuk menandakan bahwa reservation tersebut sudah beres/tidak menggantung). Contoh
  - RSV-002 dan RSV-005 status reservation != reserved lagi
![image](https://user-images.githubusercontent.com/25950059/77273547-7043f080-6ce6-11ea-9a5d-58d3ce30deba.png)
  - RSV-002 dan RSV-005 hilang recordnya dari table expected arrival today setelah diproses
![image](https://user-images.githubusercontent.com/25950059/77273734-e0527680-6ce6-11ea-98fd-444af1b8b920.png)
6. Klik id Folio pada tabel expected Close Folio untuk memproses Close atau memperpanjang tanggal Close
7. tampilan record pada table akan berubah seperti tahap 5
8. Klik tombol Process Dayend Close
9. Muncul modal konfirmasi

## Alternate Flow
2.1. Saat klik New, belum ada record Posting Room Charge dengan audit_date sama berstatus Close. User diarahkan untuk melakukan Posting Room Charge dulu.
8.1. Klik tombol Process Dayend Close sebelum menyelesaikan Reservation dan Folio yang menggantung di step 3, maka akan ada warning untuk menyelesaikan terlebih dulu.
9.1. Klik tombol No, maka akan kembali ke halaman Dayend Close
9.2. Klik tombol Yes, maka 
- semua folio transaction diposting ke journal entry. Setiap Folio Transaction yang diposting ke Journal, update atribut posting pada Folio Transaction menjadi Yes.
- membuat record baru pada doctype Audit Log

| Attribute | Type | Value
| - | - | -
| number | Int | generated automatically
| audit_date | Date | getLatestAuditDate()+1
| posting_date | Date Time | current_datetime
| posting_by | Link (User) | user.username

## Post Condition
1. Tiap Reservation yang telah diproses akan terupdate statusnya menjadi in house/cancel/no show/finish (sesuai dengan action yang dipilih)
2. Reservation yang berstatus In house di update status kamarnya menjadi Occupied Dirty
3. Setelah proses Dayend Close, sistem Logout untuk update audit_date dari transaksi

**Comment by anra54** [comment]
Issue buat precodition posting room charge di mana nih?

**Comment by sumayyah42** [comment]
di #25 dan #26

**Comment by anra54** [comment]
untuk perpindahan dari folio ke journal entry, konfirmasi terjadi ketika dayend close? penjelasannya di issue yg mana?

**Comment by sumayyah42** [comment]
iya, ada di alternate flow
> 9.2. Klik tombol Yes, maka
> - semua folio transaction diposting ke journal entry. Setiap Folio Transaction yang diposting ke Journal, update atribut posting pada Folio Transaction menjadi Yes

**Comment by sumayyah42** [comment]
update 30/4
- terdapat inisiasi record pada Inn Audit Log untuk transaksi pertama (yang belum ada record dayend close)
- atribut audit_date pada doctype Inn Audit Log dijadikan referensi untuk audit_date pada Folio Transaction. posting_date pada Journal Entry mengikuti audit_date dari Folio Transaction tersebut
- Update room_status dari actual_room doctype Reservation menjadi Ocuupied Dirty setelah Dayend Close
