### ISSUE TITLE
A.3. Issue Card

### ISSUE THREAD

**Issue by sumayyah42** [core-initiative/front-desk#3]
## Contoh Layout
![image](https://user-images.githubusercontent.com/25950059/75148203-a155f300-5731-11ea-92d5-54acae2c2316.png)
![image](https://user-images.githubusercontent.com/25950059/75147466-f4c74180-572f-11ea-8deb-60639d24a03e.png)
![image](https://user-images.githubusercontent.com/25950059/75215708-30abe680-57c4-11ea-9686-b2746144a5fe.png)

## Precondition
1. Reservation berstatus In House

## Basic Flow
1. Pilih Reservation yang telah In House
2. Klik tombol Issue Card
3. Record dalam child table Issued Card bertambah
4. Klik tombol save pada Reservation

## Sub Flow
2.1. Record yang berstatus aktif melebihi jumlah pada room_max_active_card pada doctye Inn Hotel Setting, tidak bisa menambah record baru
2.2. Error setelah menembak API Tesa, muncul modal error 
4.1. Setelah klik save, isian valid maka akan menyimpan record sebagai berikut:
- Membuat record pada doctype Issue Card

| Attribute | Type | Value |
| - | - | - |
| card_number | varchar(140) | from card reader |
| room_id | varchar(140) | reservation.room_id |
| is_active | boolean | true |
| issued_date | date | current_date |
| expired_date | date | reservation.expected_departure |
| erased_date | date | null |

## Post Condition
1. Record pada child table Issued Card bertambah

**Comment by sumayyah42** [comment]
![image](https://user-images.githubusercontent.com/25950059/77507247-a2964f00-6e9a-11ea-8ad6-f5445494fc2a.png)
Update kalimat notification ketika klik issue card, hapus kata "dari fungsi tesa_check_in"

**Comment by anra54** [comment]
@sumayyah42 untuk tes dengan mock server API:
ke [www.mocky.io](https://www.mocky.io), terus masukkan 
```
{
  "returnCardId": "1233421"
}
```
ke isian Body, klik Generate My HTTP Response

copy link mocky.io yang tergenerate ke Card API URL di Inn Hotel Settings
