### ISSUE TITLE
A.4. Erase Card

### ISSUE THREAD

**Issue by sumayyah42** [core-initiative/front-desk#4]
## Precondition
1. Ada issued card berstatus aktif pada reservation

## Basic Flow
1. Pilih Reservation In House
2. Klik panah pada record issued card yang berstatus aktif
3. Klik tombol Erase Card (tembak API Tesa, update kartu dari reader)

- Contoh layout pada record Issued Card

![image](https://user-images.githubusercontent.com/25950059/75215745-49b49780-57c4-11ea-8765-bacfa9b44204.png)
Tampilan setelah panah diklik
![image](https://user-images.githubusercontent.com/25950059/75154489-54c5e400-5740-11ea-9980-1fb2bd22d224.png)

## Post Condition
1. Update status Issued card, active = false

**Comment by purwaren** [comment]
@anra54 : Untuk erase card pangil API untuk issue card, tapi untuk room di set ke 999, referensi ke #3
