### ISSUE TITLE
E.1. AR City Ledger

### ISSUE THREAD

**Issue by sumayyah42** [core-initiative/front-desk#41]
## Precondition
1. Terdapat pembayaran dengan Mode of Payment City Ledger pada Folio berstatus Close

## Basic Flow
1. Membuat payment dengan City Ledger pada Folio
2. Close Folio
3. Klik menu AR City Ledger
4. Terdapat record dari pembayaran Folio di step 1 pada doctype AR City Ledger
Data yang disimpan pada AR City Ledger
   - Customer (tampil dalam list view)
   - Channel (tampil dalam list view)
   - Amount (tampil dalam list view)
Amount dari payment menggunakan city ledger. Jika terdapat > 1 Folio transaction payment menggunakan city ledger, maka amount adalah akumulasi dari semua payment city ledger pada 1 Folio
   - Folio Number
   - Folio Type
   - Folio Open
   - Folio Close

## Alternate Flow
2.1. Klik menu AR City Ledger sebelum Close Folio, maka record pembayaran City Ledger dari Folio tsb tidak muncul

**Comment by anra54** [comment]
piutang city ledgernya masih ke 1133.001? @sumayyah42

**Comment by sumayyah42** [comment]
Iya masih
