### ISSUE TITLE
E.2. AR City Ledger Invoice

### ISSUE THREAD

**Issue by sumayyah42** [core-initiative/front-desk#42]
## Contoh Layout
![image](https://user-images.githubusercontent.com/25950059/79308654-30f27380-7f23-11ea-9980-ed2f9c3400e6.png)

## Precondition
1. Terdapat record berstatus Unpaid pada AR City Ledger

## Basic Flow
1. Klik menu AR City Ledger Invoice
2. Klik tombol New
3. Pilih Issued Date (Default date today)
4. Pilih Due Date
5. Pilih Channel
6. Pilih Contact Person (jika ada)
7. Pilih Folio pada child table (Folio yang tampil berasal dari doctype AR City Ledger difilter berdasarkan channel yang dipilih pada step 5)
8. Klik tombol Save

## Alternate Flow
8.1. Isian required telah diisi, maka akan menyimpan record AR City Ledger Invoice
Field | Type | Value
-|-|-
status | Select (Paid, Unpaid) | Unpaid
issued_date | Date | form.issued_date
due_date | Date | form.due_date
channel | Link (Channel) | form.channel
contact_person | Link (Customer) | form.contact_person
amount | Currency | calculated automatically: sum of amount table folio
total_paid | Currency | calculated automatically: sum of amount table payment 
outstanding_amount | Currency | calculated automatically: = amount - total_paid
folio | Table | 
payment | Table |

# Post Condition
1. Terdapat record baru pada AR City Ledger Invoice berstatus Unpaid
2. Muncul tabel payment di bawah tabel folio setelah klik berhasil Save

**Comment by anra54** [comment]
@sumayyah42 karena folio bisa berdiri sendiri sekarang ( Master/Desk) bisa ada AR City Ledger yang ga ada channelnya, karena ga ada reservationnya.. harus diapain jadinya yg kasus begini?

**Comment by sumayyah42** [comment]
karena yang master/desk ga ada channel, filter untuk memilih folio ditambahkan dengan Inn group, sehingga folio yang muncul adalah folio dari form.channel || form.group. Field channel dan group diset tidak required supaya bisa memilih hanya salah satunya.

**Comment by anra54** [comment]
berarti master/desk folio selalu ngisi field Inn Group-nya ya
