### ISSUE TITLE
E.3. AR City Ledger Invoice-Payment

### ISSUE THREAD

**Issue by sumayyah42** [core-initiative/front-desk#43]
## Precondition
1. AR City Ledger Invoice berstatus Unpaid

## Basic Flow
1. Klik menu AR City Ledger Invoice
2. Pilih record berstatus Unpaid
3. Pada child table payment, pilih payment date
4. Pilih mode of payment
5. Isi jumlah nominal pembayaran 
6. Klik tombol Save
7. Muncul modal confirmation yang bertuliskan "Are you sure to save the data? If you input payment record, please make sure that **Payment Date, Amount and Mode of Payment are all correct**. After Save, you cannot delete the payment record."

## Alternate Flow
7.1. Klik, maka akan menyimpan record
 Field | Type | Value
-|-|-
mode_of_payment | Link (Mode of Payment) | form.mode_of_payment
amount | Currency | form.amount
payment_date | Date | form.payment_date

dan membuat record pada journal entry
 Field | Value
-|-
posting_date | payment_date
 
dan child table journal entry account
 No | Account | Debit | Credit
-|-|-|-
1 | mode_of_payment(AR City Ledger Payment).account | amount | 0
2 | mode_of_payment(City Ledger).account | 0 | amount

## Post Condition
1. Terdpat record baru pada child table payment di AR City Ledger Invoice
2. Terdapat record baru pada journal entry
3. Update Amount, Total Paid, dan Outstanding dari AR City Ledger Invoice berdasarkan nominal yang telah dibayarkan
4. Record payment pada AR City Ledger Invoice tidak bisa dihapus
5. Jika outstanding AR City Ledger = 0, status AR City Ledger Invoice diupdate menjadi Paid. Data sudah tidak bisa diubah jika status telah berubah menjadi Paid.

**Comment by anra54** [comment]
@sumayyah42 Usul, agak beresiko kalo bikin child table ga bisa dihapus, usul saya gimana kalo masuk journal entry dibikin trigger dari tombol, make_payment, yang bisa lanjut prosesnya jika hanya outstanding == 0.

**Comment by anra54** [comment]
mode_of_payment(AR City Ledger Payment).account 

ini accoutnya nomornya berapa ya?

**Comment by sumayyah42** [comment]
iya itu maks

> @sumayyah42 Usul, agak beresiko kalo bikin child table ga bisa dihapus, usul saya gimana kalo masuk journal entry dibikin trigger dari tombol, make_payment, yang bisa lanjut prosesnya jika hanya outstanding == 0.

oke, pastiin posting date ke jurnalnya ngambil dari audit log



> mode_of_payment(AR City Ledger Payment).account
> 
> ini accoutnya nomornya berapa ya?
> 
> atau ini maksudnya `AR_City_Ledger_Payment.mode_of_payment.account` ya @sumayyah42 ?

iya, maksudnya account pembayaran dari mode of payment yg dipilih
