### ISSUE TITLE
E.4. Print Proforma Invoice

### ISSUE THREAD

**Issue by sumayyah42** [core-initiative/front-desk#44]
Di halaman AR City Ledger Invoice, terdapat pilihan print Proforma Invoice . Referensi [proforma_invoice.json](https://github.com/purwaren/ihram-front-desk/blob/master/front_desk/front_desk/print_format/proforma_invoice/proforma_invoice.json)

**Comment by anra54** [comment]
jangan lupa ke menu customize form buat bikin Print format proforma invoice jadi defaultnya AR City Ledger Invoice. 
Bank Info ngambil ke COA. kalo kosong bikin bank account 1121.0**
