### ISSUE TITLE
A.6. Move Room

### ISSUE THREAD

**Issue by sumayyah42** [core-initiative/front-desk#6]
## Precondition
1. Reservation berstatus In house

## Basic Flow
1. Pilih Reservation berstatus In house
2. Klik tombol Move Room
3. Sistem akan membuat record baru pada Move Room
4. Pilih kamar dan room rate berdasarkan tipe kamar yang dipilih
5. Centang check box Change Room Rate
6. Pilih room rate serta isi nominal new rate
7. Tulis alasan pemindahan
8. Klik tombol save

## Alternate Flow
5.1. Change Room Rate tidak dicentang
6.1. Tidak bisa memilih room rate dan update new rate
8.1. Setelah klik save, isian valid maka akan menyimpan record sebagai berikut:
- Membuat record baru pada doctype Move Room

| Field | Type | Value | Detail | Required |
| - | - | - | - | - |
| reservation | varchar(140) | reservation.name| read-only | |
| old_room | varchar(140) | reservation.room_id | read-only | |
| room_type | varchar(140) | form.room_type | default value from reservation, used for filtering new_room | Yes |
| bed_type | varchar(140) | form.bed_type | default value from reservation, used for filtering new_room | Yes |
| arrival | varchar(140) | current_date | hide from form, used for filter new_room | |
| departure | varchar(140) | reservation.expected_departure | hide from form, used for filter new_room | |
| new_room | varchar(140) | form.new_room | filter based on room_type, bed_type, status room booking between arrival departure, and room status Vacant Ready | Yes |
| change_rate | boolean | form.change_rate | check box | |
| old_room_rate | varchar(140) | reservation.room_rate | read-only | |
| old_rate | decimal(15,2) | reservation.actual_amount | read-only | |
| new_room_rate | varchar (140) | form.new_room_rate | default value from reservation, editable if change_rate = true, read-only if false | Yes |
| new_rate | decimal(15,2) | form.new_rate | default value from reservation, editable if change_rate = true, read-only if false | Yes |
| reason | smalltext | form.reason | | Yes |

- if new_room != old_room, buat record di doctype Room Booking

| Field | Type | Value |
| - | - | - | 
| start | datetime | current_date |
| end | datetime | reservation.expected_departure|
| status | varchar(140) | Booked |
| room_id | varchar(140) | form.new_room |
| room_availability | varchar(140) | RS |

## Post Condition
1. Room_id pada Reservation terupdate dengan value move_room.new_room
2. Room_rate_name Reservation terupdate dengan value move_room.new_room_rate
3. Actual_rate Reservation terupdate dari value move_room.new_rate
4. Update status kamar dari kamar move_room.old_room menjadi Vacant Dirty
5. Update status kamar dari kamar move_room.new_room menjadi Occupied Clean
6. If new_room != old_room, lakukan update berikut
```
update room_booking 
set status = Finish, end=current_date 
where reservation=move_room.reservation 
```

**Comment by anra54** [comment]
workflow done, tinggal implementasi cascading dropdown filter room_type, bed_type, room_id

**Comment by sumayyah42** [comment]
Setelah proses move room:
- old_room.room_status dari Move Room set menjadi Vacant Dirty
- old_room.door_status dari Move Room set menjadi No Status
- new_room.room_status dari Move Room set menjadi Occupied Clean
