### ISSUE TITLE
A.13. Cancel When In House

### ISSUE THREAD

**Issue by sumayyah42** [core-initiative/front-desk#66]
Tambahkan tombol Cancel pada Menu (pojok kanan atas) di reservasi berstatus In House. Ketika diklik maka 
1.  Cek balance dari Folio sudah 0 atau belum, 
    - jika belum maka akan muncul warning untuk menyelesaikan tagihan di Folio
    - jika sudah maka akan muncul confirmation box
2. Jika klik Yes maka 
   - update Reservation menjadi Cancel 
   - update actual_room dari reservation menjadi Vacant Dirty 
   - update Room Booking end menjadi current date dan status menjadi Canceled

**Comment by anra54** [comment]
@sumayyah42 
ini bedanya apa ya dengan chekout sebelum tanggal departure?

**Comment by anra54** [comment]
push at a52e2e86af2873ab69d689dbe772a8603610c55b
@sumayyah42 , Kalo Room Booking statusnya jadi Canceled, di Room Availability Page status Room Soldnya ga tampil. Apa baiknya statusnya jadi Finish aja? room statusnya jadi Vacant Dirty juga soalnya, bukan Vacant Ready.
