### ISSUE TITLE
A.7. Check Out

### ISSUE THREAD

**Issue by sumayyah42** [core-initiative/front-desk#7]
## Precondition
1. Reservation berstatus In house

## Basic Flow
1. Pilih reservation yang akan di check out
2. Klik tombol check out
3. Muncul modal konfirmasi, klik tombol yes

## Alternate Flow
3.1. Guest Folio belum balance (balance != 0), muncul modal yang mengarahkan untuk menyelesaikan pembayaran pada Folio
3.2. Masih terdapat record issued card berstatus aktif, muncul modal yang mengarahkan untuk menonaktifkan dan kembali ke reservation
(Jika reservation menemui kedua case di atas, modal yg muncul adalah terkait pelunasan di Folio)  

## Post Condition
1. Status reservation update menjadi Finish
2. Status Folio update menjadi Close
3. room_status kamar pada reservation update menjadi Vacant Dirty
4. Update: Membuat pencatatan jurnal against account dari debit_account pada Folio Transaction tipe Credit dan credit_account pada Folio Transaction tipe Debit **ketika Dayend Close.** Contoh:

F-1234
Folio Transaction

Transaction | type | Debit | Credit
|- | - | - | -
Room Payment | Debit | 300.000 |
Room Charge | Credit | | 300.000

Pencatatan Jurnal dari tiap transaction ketika Dayend Close yaitu
1. Room Payment
Debit Account : sesuai Mode of Payment
Credit Account : 2110.005 - A/P Guest Deposit/Payment

2. Room Charge
Debit Account: 1133.003 - A/R Guest Ledger
Credit Account : 4210.001 - Room Revenue

Ketika proses Check Out, sistem akan membuat record ke jurnal yaitu
1. Debit Account : 2110.005 - A/P Guest Deposit/Payment (membalik credit_account transaksi tipe Debit) 
2. Credit Account : 1133.003 - A/R Guest Ledger (membalik debit_account transaksi tipe Credit)

**Comment by anra54** [comment]
Tersisa pencatatan jurnal. Implementasi shift dan dayend close dulu
