### ISSUE TITLE
[Improve] A.3 Issue Card

### ISSUE THREAD

**Issue by purwaren** [core-initiative/front-desk#77]
Untuk issue card ada perubahan json request dan url yang diakses

URL | http://10.1.0.4:15000/tesa/checkin
--- | ---

## Request Body
```json
{
  "cmd": "CI",
  "room": "999",
  "activationDate": "22/06/2020",
  "activationTime": "12:00",
  "expiryDate": "23/06/2020",
  "expiryTime": "12:00",
  "returnCardId": "1"
}
```
Field | Deskripsi
--- | ---
room | sesuai dengan nomor kamar yang di check-in
activationDate | current date
activationTime | 12:00 
expiryDate | sesuai dengan actual departure
expiryTime | 12:00

## Sample Response
```json
{
  "info": "Success",
  "rawMsg": "�CI�24A9B41D��",
  "rawMsgHex": "02B34349B33234413942343144B303C5",
  "rawMsgBase64": "ArNDSbMyNEE5QjQxRLMDxQ=="
}
```

**Comment by sumayyah42** [comment]
@anra54 Terdapat beberapa update untuk request body
- "room" yang dilempar hanya angka dari kamar. jadi dari room R-201, yang dilempar hanya 201 nya
- jika sudah ada satu record issued card yang active, ketika klik tombol issue card lagi command yang dikirim adalah "CG" bukan "CI"

**Comment by anra54** [comment]
fix pushed at 4633d804be20d159af4eb829031c03d3ecc4758c

**Comment by purwaren** [comment]
@anra54 : Ada improvement untuk flow extend kamar.

## Flow Issue card untuk extend kamar
1. Deactivate semua card dulu
2. Issue card lagi dengan command CI karena semua card sudah tidak aktif, dan expiry date nya mengikuti actual expiry date yang sudah diupdate karena tamu extend kamar
