### ISSUE TITLE
[Improve] A.4 Erase Card

### ISSUE THREAD

**Issue by purwaren** [core-initiative/front-desk#79]
Di API yang disediakan tesa sebenarnya tidak ada fungsi untuk erase card. Untuk memenuhi kebutuhan ini jadinya erase card dilakukan dengan melakukan pemanggilan API untuk checkin tesa, tetapi kamarnya diarahkan ke kamar 999. Silahkan refer ke issue #77 

== Request Body
```json
{
  "cmd": "CI",
  "room": "999",
  "activationDate": "22/06/2020",
  "activationTime": "12:00",
  "expiryDate": "23/06/2020",
  "expiryTime": "12:00",
  "returnCardId": "1"
}
```

**Comment by anra54** [comment]
pushed at 9dec5d839c3441135d8cb18200e01ae317dfd949
