### ISSUE TITLE
[Improve] Add Total Night In Reservation

### ISSUE THREAD

**Issue by sumayyah42** [core-initiative/front-desk#80]
![image](https://user-images.githubusercontent.com/25950059/85705155-2d415100-b70b-11ea-9b8d-51d1b4dd6ee3.png)
Di bawah Expected Departure, tambahkan field Total Night (read only) yang menghitung jumlah malam menginap tamu dari expected arrival hingga expected departure

**Comment by anra54** [comment]
push at f576bc474fe00651c91603486f2c55672fee001d
