### ISSUE TITLE
[Bug] Credit Account Package Tax

### ISSUE THREAD

**Issue by sumayyah42** [core-initiative/front-desk#83]
Pada Folio Transaction Type Package Tax, perbaiki penulisan credit dan debit account menjadi sebagai berikut
- debit_account: debit_account dari Package
- credit_account: account tax dari inn_tax_id dalam Package

**Comment by anra54** [comment]
@sumayyah42 ini di halaman apa ya?

**Comment by anra54** [comment]
push at 9056a0e37220937a82d3b7f6837473b9b9591f6c
