### ISSUE TITLE
[Improve] Void Transaction Flow

### ISSUE THREAD

**Issue by sumayyah42** [core-initiative/front-desk#86]
Untuk Void Transaction, tambahkan isian void reason serta acc dari hotel reservation manager untuk bisa mengubah is void menjadi true. Acc bisa dalam bentuk input kode yang terdapat pada inn hotel settings Hotel Reservation Manager. Yang perlu dicatat di sistem pada saat melakukan void transaksi  adalah
- void reason
- name dari user yang melakukan void
- timstamp dilakukannya void
- timestamp acc void

**Comment by anra54** [comment]
## Solusi
- Doctype baru `Inn Void Folio Transaction` untuk menampung data request/response void transaction
- Void transaction hanya bisa di halaman Folio, tidak bisa di halaman Folio Transaction
- Klik Void Transaction memunculkan dialog baru, bukan langsung void
- Introduce Supervisor passcode yang bisa diakses dari tombol Show Supervisor Passcode. Muncul untuk role `Housekeeping Supervisor`. bisa dikomunikasikan untuk ditambah bagi role2 lainnya

## Kemungkinan Alur
 ### Void dengan supervisor passcode
- Di halaman folio, klik transaction yg mau divoid
- Klik Void Transaction, check use passcode, isi passcode sesuai dari inn hotels setting, dan alasan void. Klik Request Void
- Jika passcode tidak sesuai, ada pesan error.
- Jika passcode sesuai, akan dibuat entry baru di Inn Void Folio Trasanction dgn detail:
   - status: Approved
   - applicant_reason: provided dari requester
   - use supervisor code: 1
   - void applicant: requested id
   - void approver: requested id
   - void timestamp: now
   - is_void dari folio trx berubah jadi 1
   - void_id dari folio trx berisi id Inn Void Folio Transaction yg baru dibuat
### Void tanpa supervisor passcode
- Di halaman folio klik trx yg mau divoid
- Klik Void Transaction
   - Jika sudah ada request di Inn Void Folio Transaction berstatus Requested, ada pesan muncul request sudah dibuat, tunggu approval dari supervisor
   - Jika sudah ada request di Inn Void Folio Transaction berstatus Denied. Maka user bisa submit request ulang, atau langsung dengan void dengan passcode. Variable void_id di folio trx akan diganti dengan Inn Void Folio Transaction yg baru
   - Jika belum ada request maka akan dibuat Inn Void Folio Transaction baru dgn detail:
    -- status: Requested
    -- applicant_reason: provided dari requester
    -- use supervisor code: 0
    -- void applicant: requested id
    -- void approver: kosong
    -- void timestamp: kosong

### Supervisor respons request Void
- Masuk halaman Inn Void Folio Transaction
- Klik request dengan status `Requested`
- Klik tombol Respond to Request
- Isi sesuai dengan kebutuhan, Approve atau Deny
- Klik Save Response
- variable void_approver, void_timestamp akan terisi, denied_reason akan terisi jika request dideny

**Comment by anra54** [comment]
Roles that privileged to see passcode and responds to void request
Hotel Manager
Hotel Reservation User
Administrator

**Comment by anra54** [comment]
workflow affected:
- Dayend Close
- Close Folio
- Checkout Reservation

**Comment by sumayyah42** [comment]
@anra54 need to improve: jika  journal_entry_id folio transaction sudah tidak null maka user tidak bisa melakukan void, either dihilangkan tombolnya atau terdapat pop up notification ketika tombol Void Transaction di klik

**Comment by anra54** [comment]
> @anra54 need to improve: jika journal_entry_id folio transaction sudah tidak null maka user tidak bisa melakukan void, either dihilangkan tombolnya atau terdapat pop up notification ketika tombol Void Transaction di klik

fix push @ 9f72005ab35179cf224bb510e8bd92c2954c19ac

**Comment by sumayyah42** [comment]
Saat check out di transaksi yang ada void menggantung, muncul error seperti ini


Traceback (most recent call last):
  File "/home/ihram/frappe-bench/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/ihram/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/ihram/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ihram/frappe-bench/apps/frappe/frappe/__init__.py", line 1036, in call
    return fn(*args, **newargs)
  File "/home/ihram/frappe-bench/apps/inn/inn/inn_hotels/doctype/inn_reservation/inn_reservation.py", line 190, in check_out_reservation
    folio_status = close_folio(folio_doc.name)
  File "/home/ihram/frappe-bench/apps/inn/inn/inn_hotels/doctype/inn_folio/inn_folio.py", line 155, in close_folio
    "<br /> Transaction need to be resolved: <br />" + list
TypeError: must be str, not list
