### ISSUE TITLE
B. Folio

### ISSUE THREAD

**Issue by sumayyah42** [core-initiative/front-desk#9]
## Kolom yang tampil dalam Folio List 
- Folio number
- Type : Guest, Master, Desk
- Folio Status : Open, Closed, Cancel
- Customer

## Contoh layout Folio
![image](https://user-images.githubusercontent.com/25950059/77273032-30303e00-6ce5-11ea-9e25-6fd70720794b.png)
![image](https://user-images.githubusercontent.com/25950059/77272512-01fe2e80-6ce4-11ea-933e-eec83eb40056.png)
![image](https://user-images.githubusercontent.com/25950059/75542692-e0968380-5a52-11ea-936b-97cdb2855e6e.png)

## Doctype Folio
| Attribute | Type |
| - | - |
| open | Datetime |
| close | Datetime |
| type | Select (Guest, Master, Desk) |
| group_name | Link (Group) |
| status | Select (Open, Close, Cancel) |
| customer_id | Link (Customer) |
| bill_instruction | Small Text | 
| folio_transaction | Table (Folio Transaction) |
| total_debit | Currency |
| total_credit | Currency |
| balance | Currency |

## Doctype Folio Transaction
| Field | Doctype Type |
| - | - |
| audit_date | date |
| charge_name | Link |
| type | Select(Credit, Debit) |
| debit_account | Link | 
| credit_account | Link |
| amount | Currency |
| sub_folio | Select(A,B,C,D) |
| remark | Data |
| posting | Select(No, Yes) | 
| is_void | Select(No, Yes) |
| shift_id | Link |
| is_refund | Select(Yes, No) |

## Doctype Transaction Type
| Attribute | Type |
| - | - |
| name | Data |
| debit_account | Link(Account) |
| credit_account | Link(Account) |
| type | Select(Credit, Debit) |
| is_included | Check |

**Comment by sumayyah42** [comment]
Transaction Type List type Credit:
- DP
- Deposit
- Room Payment

Transaction Type List type Debit
- Early Check In
- Late Check Out
- Cancellation Fee
- Additional Charge
- Credit Card Administration Charge

**Comment by sumayyah42** [comment]
Update 9/3 : atribut parent pada Folio dihapus

**Comment by sumayyah42** [comment]
Update 16/3
doctype Folio tambah atribut
- total_credit: Currency
menjumlahkan semua Folio Transaction bertipe credit
- total_debit: Currency
menjumlahkan semua Folio Transaction bertipe debit
- balance: Currency
balance = total_debit - total_credit
jika balance positif, tamu masih kurang bayar
jika balance negatif, harus dilakukan refund

**Comment by sumayyah42** [comment]
Update:
Tambah atribut start dan end pada Folio

**Comment by sumayyah42** [comment]
> start	Datetime
> end	Datetime

Update tambah atribut start dan end pada Folio

**Comment by anra54** [comment]
Update: filter untuk tidak dimasukkan dalam pilihan dropdown di halaman Folio dipindahkan menjadi variable `is_included` dalam doctype Inn Folio Transaction Type. Otomatis tergenerate (kecuali isian account debit credit) setelah terinstall
