### ISSUE TITLE
[Improve] Update Room Booking When Update Reserved Room In Reservation

### ISSUE THREAD

**Issue by sumayyah42** [core-initiative/front-desk#93]
Ada case di mana FO meng-update Reservation ketika status masih Reserved. Ketika data berubah, update data pada Inn Room Booking pada atribut sebagai berikut.
Reservation | Should be Update In Room Booking 
-|-
room_id (Reserved Room) | room_id
expected_arrival | start
expected_departure | end

**Comment by anra54** [comment]
Saya baca kodingan saya sudah dihandle:
https://github.com/purwaren/front-desk/blob/6adf0dd86b376d3ccd561a618680437721ee7e04/inn/inn_hotels/doctype/inn_room_booking/inn_room_booking.py#L76-L91
